CREATE SCHEMA IF NOT EXISTS xy;


INSERT INTO POI (COORDINATEX, COORDINATEY, NAME) VALUES ( 27, 12, 'Lanchonete' );
INSERT INTO POI (COORDINATEX, COORDINATEY, NAME) VALUES ( 31, 18, 'Posto' );
INSERT INTO POI (COORDINATEX, COORDINATEY, NAME) VALUES ( 15, 12, 'Joalheria' );
INSERT INTO POI (COORDINATEX, COORDINATEY, NAME) VALUES ( 19, 21, 'Floricultura' );
INSERT INTO POI (COORDINATEX, COORDINATEY, NAME) VALUES ( 12, 8, 'Pub' );
INSERT INTO POI (COORDINATEX, COORDINATEY, NAME) VALUES ( 23, 6, 'Supermercado' );
INSERT INTO POI (COORDINATEX, COORDINATEY, NAME) VALUES ( 28, 2, 'Churrascaria' );